// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgM_GwspjX2JSY1ZmMpyiOIFATEariLag',
    appId: '1:448960617204:web:2960038265375c74631ca1',
    messagingSenderId: '448960617204',
    projectId: 'appbank-3de87',
    authDomain: 'appbank-3de87.firebaseapp.com',
    databaseURL: 'https://appbank-3de87-default-rtdb.firebaseio.com',
    storageBucket: 'appbank-3de87.appspot.com',
    measurementId: 'G-25CBVN1HJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9UKCwIakG65f7NStIRo0b7RWb0SdENE',
    appId: '1:448960617204:android:0ab722f73d716478631ca1',
    messagingSenderId: '448960617204',
    projectId: 'appbank-3de87',
    databaseURL: 'https://appbank-3de87-default-rtdb.firebaseio.com',
    storageBucket: 'appbank-3de87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiD8r7VmEG5gsWBu1QHXcaNctGamyJzyw',
    appId: '1:448960617204:ios:8508f578db4493c8631ca1',
    messagingSenderId: '448960617204',
    projectId: 'appbank-3de87',
    databaseURL: 'https://appbank-3de87-default-rtdb.firebaseio.com',
    storageBucket: 'appbank-3de87.appspot.com',
    iosBundleId: 'com.example.appbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiD8r7VmEG5gsWBu1QHXcaNctGamyJzyw',
    appId: '1:448960617204:ios:a97812fbfb03425d631ca1',
    messagingSenderId: '448960617204',
    projectId: 'appbank-3de87',
    databaseURL: 'https://appbank-3de87-default-rtdb.firebaseio.com',
    storageBucket: 'appbank-3de87.appspot.com',
    iosBundleId: 'com.example.appbank.RunnerTests',
  );
}
